# Generated by Django 4.0.6 on 2022-07-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linktreeApp', '0004_profile_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
